import { Router } from "express";
import { apikeyCheck, permissions } from "../authUtils/checkUtils";
import userRouter from './user'; 
import todoRouter from './todo'; 
const router = Router();
router.use(apikeyCheck);
router.use(permissions('ADMIN'));
router.use('/v1/api/user', userRouter); 
router.use('/v1/api/todo', todoRouter); 
export default router;